version: '3.9'

services:
  postgres:
    image: postgres:14.0
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookstore
    ports:
      - "5432:5432"
    volumes:
      - "./2-database/init.sql:/docker-entrypoint-initdb.d/init.sql"

